export const SET_CURRENT_CHOROPLETH_ATTRIBUTE = 'SET_CURRENT_CHOROPLETH_ATTRIBUTE';
export const SET_SELECTED_REGIONS = 'SET_SELECTED_REGIONS';
export const SET_HEATMAP_DURATION = 'SET_HEATMAP_DURATION';
export const SET_START_DATE = 'SET_START_DATE';
export const SET_END_DATE = 'SET_END_DATE';
