name: Disaster Management Dashboard

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 

      - name: Install Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 20.12.1 

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build
        env:  # Add the CI variable specifically for this step 
          CI: false   

      - name: Trigger Netlify Build
        run: curl -X POST -d '{}' https://api.netlify.com/build_hooks/6612247851a9b46d7e97f457